"""initial migration

Revision ID: 408f76502ea9
Revises: d3a59da34e44
Create Date: 2026-02-06 02:41:07.356767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "408f76502ea9"
down_revision: Union[str, Sequence[str], None] = "d3a59da34e44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE proffessions CASCADE")
    op.add_column(
        "categories",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "categories",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "comments",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "comments",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "media",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "media",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("posts", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.add_column("posts", sa.Column("category_id", sa.BigInteger(), nullable=True))
    op.add_column("posts", sa.Column("views_count", sa.BigInteger(), nullable=False))
    op.add_column("posts", sa.Column("likes_count", sa.BigInteger(), nullable=False))
    op.add_column("posts", sa.Column("comments_count", sa.BigInteger(), nullable=False))
    op.add_column("posts", sa.Column("mins_read", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "posts", "categories", ["category_id"], ["id"])
    op.create_foreign_key(None, "posts", "users", ["user_id"], ["id"])
    op.drop_column("posts", "content")
    op.add_column(
        "professions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "professions",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "tags",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "tags",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("profession_id", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("post_count", sa.BigInteger(), nullable=False))
    op.add_column(
        "users", sa.Column("post_read_count", sa.BigInteger(), nullable=False)
    )
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_staff", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS proffession_id CASCADE")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("proffession_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_proffession_id_fkey"),
        "users",
        "proffessions",
        ["proffession_id"],
        ["id"],
    )
    op.drop_column("users", "is_deleted")
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "is_staff")
    op.drop_column("users", "is_active")
    op.drop_column("users", "post_read_count")
    op.drop_column("users", "post_count")
    op.drop_column("users", "profession_id")
    op.drop_column("tags", "updated_at")
    op.drop_column("tags", "created_at")
    op.drop_column("professions", "updated_at")
    op.drop_column("professions", "created_at")
    op.add_column(
        "posts", sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "mins_read")
    op.drop_column("posts", "comments_count")
    op.drop_column("posts", "likes_count")
    op.drop_column("posts", "views_count")
    op.drop_column("posts", "category_id")
    op.drop_column("posts", "user_id")
    op.drop_column("media", "updated_at")
    op.drop_column("media", "created_at")
    op.drop_column("comments", "updated_at")
    op.drop_column("comments", "created_at")
    op.drop_column("categories", "updated_at")
    op.drop_column("categories", "created_at")
    op.create_table(
        "proffessions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("proffessions_pkey")),
    )
    # ### end Alembic commands ###
