"""rename password to password_hash

Revision ID: 8782ca426b21
Revises: 3938d04e758b
Create Date: 2026-02-08 18:45:56.253978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8782ca426b21"
down_revision: Union[str, Sequence[str], None] = "3938d04e758b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password_hash", sa.String(length=100), nullable=True)
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
