"""initial migration

Revision ID: b7366c27e2ae
Revises:
Create Date: 2026-01-31 14:13:49.748546

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b7366c27e2ae"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
