"""add: deleted email

Revision ID: c86653f0d86f
Revises: f7cafa1962fa
Create Date: 2026-02-27 12:27:50.858182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c86653f0d86f"
down_revision: Union[str, Sequence[str], None] = "f7cafa1962fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "comments", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "post_tags", "tags", ["tag_id"], ["id"])
    op.create_foreign_key(None, "posts", "users", ["user_id"], ["id"])
    op.add_column(
        "users", sa.Column("deleted_email", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_email")
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_constraint(None, "post_tags", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    # ### end Alembic commands ###
